name: CI

on:
  push:
    branches:
      - main  

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: AKIARWPFITOBNXY2EJHL
          aws-secret-access-key: ${{ secrets.JULIETWANJIKU1 }} 
          aws-region: us-east-1  
    
      - name: Login to AWS Public ECR
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public 

      # Step 4: Build the Docker image
      - name: Build the Docker image
        run: |
          docker build -t public.ecr.aws/k1o2c9m2/userepo:latest .

      # Step 5: Push the Docker image to Public ECR
      - name: Push the Docker image to Public ECR
        run: |
          docker push public.ecr.aws/k1o2c9m2/userepo:latest
