name: ci

on:
  push:
    branches: main

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to ECR
        uses: docker/login-action@v3
        with:
          registry: 116981799810.dkr.ecr.US East (N. Virginia).amazonaws.com
          username: AKIARWPFITOBNXY2EJHL
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
