name: ECR Login

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Amazon ECR
        uses: docker/login-action@v3
        with:
          registry: 116981799810.dkr.ecr.us-east-1.amazonaws.com
          username: github-ci-user
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          ecr: auto
          logout: true
