name: ECR Login

on:
  workflow_dispatch: # Allows manual trigger of the workflow
  push:
    branches:
      - main

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Log in to AWS Public ECR
      - name: Login to Public ECR
        uses: docker/login-action@v3
        with:
          registry: public.ecr.aws
          username: AKIARWPFITOBNXY2EJHL
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
