name: CI

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to AWS ECR
      - name: Login to ECR
        uses: docker/login-action@v3
        with:
          registry: 116981799810.dkr.ecr.us-east-1.amazonaws.com
          username: AKIARWPFITOBNXY2EJHL
          password: ${{ secrets.JULIETWANJIKU1 }}  # Ensure this secret is set correctly in GitHub Secrets

      # Step 3: Set up Docker Buildx (optional but recommended for advanced builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 4: Build the Docker image from the Dockerfile in the root directory
      - name: Build the Docker image
        run: |
          docker build -t 116981799810.dkr.ecr.us-east-1.amazonaws.com/userepo:latest .

      # Step 5: Push the Docker image to ECR
      - name: Push the Docker image to ECR
        run: |
          docker push 116981799810.dkr.ecr.us-east-1.amazonaws.com/userepo:latest
